version: '3.9'
services:
    demo_api:
        restart: always
        image: enocean/iotconnector_demo_api
        ports:
            - "5100"
        environment:
            # Use ´52.172.254.232´ when connecting to another docker container
            - IOT_AUTH_URL=https://52.172.254.232:8080/auth/aruba
            - IOT_API_URL=https://52.172.254.232/api.beta/v1/devices
            - IOT_ENDPOINT_USERNAME=user1
            - IOT_ENDPOINT_PASSWORD=gkj35zkjasb5
            - IOT_API_USERNAME=user1
            - IOT_API_PASSWORD=5a4sdFaedsa
    demo:
        restart: always
        ports:
            - "3000:3000"
        image: enocean/iotconnector_demo
        depends_on:
            - demo_api
